name: "Setup Anchor"
description: "Setup Anchor"
runs:
  using: "composite"
  steps:
      - uses: actions/cache@v2
        name: Cache Solana Tool Suite
        id: cache-anchor
        with:
          path: |
            ~/.cache/solana/
            ~/.local/share/solana/
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: solana-${{ runner.os }}-v0000-${{ env.ANCHOR_VERSION }}-${{ env.SOLANA_CLI_VERSION}}
      - run: sudo apt-get update && sudo apt-get install -y pkg-config build-essential libudev-dev
        shell: bash
      - run: sh -c "$(curl -sSfL https://release.solana.com/v${{ env.SOLANA_CLI_VERSION }}/install)"
        shell: bash
      - run: echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
        shell: bash
      - run: solana-keygen new --no-bip39-passphrase
        shell: bash
      - run: solana config set --url localhost
        shell: bash
      - run: cargo install --git https://github.com/project-serum/anchor --tag v${{ env.ANCHOR_VERSION }} anchor-cli --locked
        shell: bash