name: "Setup Anchor"
description: "Setup Anchor"
runs:
  using: "composite"
  steps:
      - uses: actions/cache@v2
        name: Cache Solana and Anchor
        id: cache-anchor
        with:
          path: |
            ~/.cache/solana/
            ~/.local/share/solana/
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
          key: solana-${{ runner.os }}-v0001-${{ env.ANCHOR_VERSION }}-${{ env.SOLANA_CLI_VERSION}}
      - run: sh -c "$(curl -sSfL https://release.solana.com/v${{ env.SOLANA_CLI_VERSION }}/install)"
        shell: bash
      - run: echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH
        shell: bash
      - run: solana-keygen new --no-bip39-passphrase
        shell: bash
      - run: solana config set --url localhost
        shell: bash
      - run: |
          if [[ $(anchor --version) != "anchor-cli {{ env.ANCHOR_VERSION }}" ]]; \
          then \
          cargo install --git https://github.com/project-serum/anchor --tag v${{ env.ANCHOR_VERSION }} anchor-cli --locked --force; \
          fi
        shell: bash