name: "Setup Base"
description: "Setup base install (linux build packages)"
runs:
  using: "composite"
  steps:
      - run: sudo apt-get update && sudo apt-get install -y pkg-config build-essential libudev-dev
        shell: bash