name: Benchmark

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  SOLANA_CLI_VERSION: 1.8.5
  ANCHOR_VERSION: 0.22.1
  NODE_VERSION: 17.0.1

jobs:
  test-core:
    name: Core Tests
    runs-on: ubuntu-18.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-base/
      - uses: ./.github/actions/setup-anchor/
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - uses: ./.github/actions/yarn/
      - uses: actions/cache@v2
        name: Cache Cargo registry + index
        id: cache-cargo-build
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./target
          key: cargo-${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}
      - run: echo $PWD && echo $HOME
      - run: anchor build
      - run: ls -al ./target/deploy
      - run: anchor test
